export enum ApiPath {
  Login = "/auth/login",
  Logout = "/auth/logout",
  TwoFactorGrcode = "/auth/2fa/grcode",
  TwoFactorVerify = "/auth/2fa/verify",
  Verify = "/auth/verify",
  Application = "/application",
  ApplicationId = "/application/{application_id}",
  ApplicationGenerateKey = "/application/{application_id}/generateKey",
  Users = "/auth/users",
  UsersInRole = "/auth/roles/{role_id}/users",
  UsersRoleAvailable = "/auth/users/{user_id}/role-mappings/available",
  UsersId = "/auth/users/{user_id}",
  Oauth2Verify = "/oauth2/verify",
  Oauth2VerifyCode = "/oauth2/verify/code",
  Oauth2Config = "/oauth2/config",
  Credentials = "/auth/users/{user_id}/credentials",
  ResetPassword = "/auth/reset-password",
  Roles = "/auth/roles",
  RolesId = "/auth/roles/{role_id}",
  RoleMappings = "/auth/users/{user_id}/role-mappings",
  Session = "/session/{user_id}",
  Mailer = "/mailer",

  Datasource = "/datasource",
  DatasourceId = "/datasource/{datasource_id}",
}
